import "./globals.css";

// Metadados da aplicação, como título e descrição
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente de layout raiz da aplicação
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
